### ISSUE TITLE
文本提示实现分割任务

### ISSUE THREAD

**Issue by viotbery** [YuetianW/YuetianW#2]
你好,Yuetian!
我在SAM的 [Issues575](https://github.com/facebookresearch/segment-anything/issues/575)中发现了你的留言，我和你有同样的困惑，我也想找到够直接对文本和图像进行训练，然后直接根据文本提示分割对应物体的模型(而不是通过一个文本-图像检测器得到框或点提示，再作为prompt传给SAM进行分割)。我找到一个可能符合要求的repo[biastuning](https://github.com/JayParanjape/biastuning),想知道你在这方面有什么新的发现能否分享一下？如有打扰请见谅！

**Comment by YuetianW** [comment]
你好，可以去[UX-Decoder/Segment-Everything-Everywhere-All-At-Once: [NeurIPS 2023\] Official implementation of the paper "Segment Everything Everywhere All at Once" (github.com)](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once)找找有没有想要的🤣，祝好！

**Comment by YuetianW** [comment]
但我觉得最流畅的方案还是等SAM开放text prompt的能力😶

**Comment by viotbery** [comment]
> 你好，可以去[UX-Decoder/Segment-Everything-Everywhere-All-At-Once: [NeurIPS 2023] Official implementation of the paper "Segment Everything Everywhere All at Once" (github.com)](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once)找找有没有想要的🤣，祝好！

感谢回复
